spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:MainServDB;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
  mvc:
    log-request-details: true

#debug: true
logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO
        orm:
          jpa: INFO
      hibernate:
        orm:
          jdbc:
            bind: trace
#      apache:
#        http: DEBUG
#    httpclient:
#      wire: DEBUG