server:
  port: 0

grpc:
  server:
    port: 0

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/stats_db
    username: root
    password: root
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    user-actions-consumer-group-id: analyzer.user.actions
    events-similarity-consumer-group-id: analyzer.events.similarity
  topic:
    user-actions-topic: stats.user-actions.v1
    events-similarity-topic: stats.events-similarity.v1