server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6666/StatServDB
    username: dbuser
    password: 12345
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true