spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:StatServDB;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
  h2:
    console:
      enabled: true
  mvc:
    log-request-details: true

debug: true