server:
  port: 0

stats-server:
  id: stats-server

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/event_db
    username: root
    password: root
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true