CREATE TABLE IF NOT exists locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lat DECIMAL(9,6) NOT NULL,
    lon DECIMAL(9,6) NOT NULL,
    name varchar(255),
    address varchar(1000),
    CONSTRAINT pk_locations PRIMARY KEY (id),
    CONSTRAINT unique_locations_lat_lon UNIQUE (lat, lon)
);

CREATE ALIAS DISTANCE FOR "ru.practicum.ewm.common.util.Distance.getDistance";