server:
  port: 0

stats-server:
  id: stats-server

spring:
  application:
    name: main-service
  datasource:
    url: jdbc:postgresql://localhost:3333/MainServDB
    username: dbuser
    password: 12345
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10